//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bym.Resources.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bym.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static byte[] any {
            get {
                object obj = ResourceManager.GetObject("any", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] api {
            get {
                object obj = ResourceManager.GetObject("api", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bymodata4util {
            get {
                object obj = ResourceManager.GetObject("bymodata4util", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] bymsvcutil {
            get {
                object obj = ResourceManager.GetObject("bymsvcutil", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] descriptor {
            get {
                object obj = ResourceManager.GetObject("descriptor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] duration {
            get {
                object obj = ResourceManager.GetObject("duration", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] empty {
            get {
                object obj = ResourceManager.GetObject("empty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] field_mask {
            get {
                object obj = ResourceManager.GetObject("field_mask", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] grpc_csharp_plugin {
            get {
                object obj = ResourceManager.GetObject("grpc_csharp_plugin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] protoc {
            get {
                object obj = ResourceManager.GetObject("protoc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] source_context {
            get {
                object obj = ResourceManager.GetObject("source_context", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] timestamp {
            get {
                object obj = ResourceManager.GetObject("timestamp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] type {
            get {
                object obj = ResourceManager.GetObject("type", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] wrappers {
            get {
                object obj = ResourceManager.GetObject("wrappers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] _struct {
            get {
                object obj = ResourceManager.GetObject("_struct", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        public static byte[] protocZip {
            get {
                object obj = ResourceManager.GetObject("protocZip", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
